version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - 386
      - arm
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    binary: mkl
    main: main.go

archives:
  - formats: [binary]
    name_template: "mkl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    Mookie Launcher is a free and open-source software licensed under the GPL-3.0 license. 
    Binaries built with [Goreleaser](https://goreleaser.com).
